In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/evenements.csv',sep=';')

In [3]:
df

,ID,Slug,URL,Title,Description,Long description,Details,Keywords,Image,Credits for the image,...,Source agenda (uid),Contributor email,Contributor phone number,Contributor name,Contributor function,Contributor organisation,Category,Country name,Registration,Additionnal links
0,15268997,atelier-creation-dentreprise-3243132,https://openagenda.com/pole-emploi/events/atel...,Atelier Création d'Entreprise,Présentations des accompagnements mobilisables...,<p>Présentations des accompagnements mobilisab...,NaN,"Atelier,ReStart,Création d'entreprise,S'inform...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
1,50737223,la-classe-loeuvre--6944943,https://openagenda.com/ndm-2024-nouvelle-aquit...,"La classe, l'oeuvre !",Des élèves des lycées Jean Monnet (Blanquefort...,<p>Des élèves des lycées Jean Monnet (Blanquef...,Entrée libre,NaN,https://cibul.s3.amazonaws.com/72227a8a43014ed...,©Frédéric Deval,...,5795929.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),NaN,NaN
2,92831157,visite-atelier-adultesenfants,https://openagenda.com/ndm-2024-occitanie/even...,Visite-Atelier adultes/enfants,"Une visite de l'exposition ""Artistes et paysan...","<p>Une visite de l'exposition ""Artistes et pay...","Entrée libre, sur inscription pour 15 personnes",NaN,https://cibul.s3.amazonaws.com/064c6c38e4554e3...,"© les Abattoirs, Musée- Frac Occitanie Toulouse",...,5865786.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""reservation@lesab...",NaN
3,53456762,les-jeudis-de-linsertion-4071122,https://openagenda.com/francetravail/events/le...,Les jeudis de l'insertion,Les entreprises d'insertion viennent à votre r...,<p>Les entreprises d'insertion viennent à votr...,NaN,"Job dating,#TousMobilisés,Recrutement,S'inform...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
4,67676934,formation-cap-metiers-de-bouche-boucherboulang...,https://openagenda.com/francetravail/events/fo...,FORMATION CAP métiers de bouche (Boucher/Boula...,Vous souhaitez vous former et obtenir l'un des...,<p>Vous souhaitez vous former et obtenir l'un ...,NaN,"Réunion d'information,S'informer,Découverte fo...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909885,77335011,jenifer-2381838,https://openagenda.com/versailles-palais-des-c...,Jenifer - Jukebox Tour,Concert variété française,"<p>JUKE BOX TOUR Votre playlist, votre concert...",75 € Carré or / 69 € Cat 1 / 59 € Cat 2,"Jukebox,Chanson Française,Jenifer",https://cdn.openagenda.com/main/bd1c2a0b088248...,NaN,...,27597051.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""billetterie@versa...",NaN
909886,33054961,rencontre-inter-degre-srav-usep-unss-4669373,https://openagenda.com/velodays/events/rencont...,Rencontre inter-degré SRAV USEP - UNSS,Itinéraire en trois étapes d'une délégation d'...,<p>De 9 h à 15 h 30 itinéraire de la délégatio...,NaN,Scolaire - Mobilité - Rencontre,https://cdn.openagenda.com/main/3de21e5f146943...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),NaN,NaN
909887,3102394,fete-du-velo-au-centre-juno-beach-1090822,https://openagenda.com/velodays/events/fete-du...,Vélodays : Fête du vélo au Centre Juno Beach,"Lors de cette journée, venez à la rencontre de...","<p>À l'occasion des Vélodays, le Centre Juno B...",NaN,Village - Vélo - Animations,https://cdn.openagenda.com/main/3b3e47586f214d...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""contact@coeurdena...",NaN
909888,76863502,mobilite-active-a-velobus-et-velocoque-esat-pa...,https://openagenda.com/velodays/events/mobilit...,Mobilité active à vélobus et vélocoque ESAT Pa...,Balade à vélo-bus et vélo-coque dans les parc...,<p>L'association V-LOW à Caen propose de prati...,NaN,Mobilité - Balade - Handicap,https://cdn.openagenda.com/main/dce1669b0fe342...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""v-lowasso.caen@ou...",NaN
909889,14608802,nuit-de-la-chauve-souris-au-grand-voyeux-3859697,https://openagenda.com/nuit-internationale-de-...,Nuit de la chauve-souris au Grand-Voyeux,A l’occasion de la Nuit Internationale de la c...,<p>Une présentation en début d’animation vous ...,"Sur inscription, gratuit","chauve-souris,nuit,nocturne,balade",https://cdn.openagenda.com/main/45d39d235fe64c...,Théo Hurtrel,...,54441221.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://www.iledef...","[{""link"": ""https://www.iledefrance-nature.fr/s..."

In [9]:
df = df.loc[df['Region'] == 'Île-de-France']
df['Region'].value_counts()

Region
Île-de-France    171601
Name: count, dtype: int64

In [10]:
df.columns

Index(['ID', 'Slug', 'URL', 'Title', 'Description', 'Long description',
       'Details', 'Keywords', 'Image', 'Credits for the image', 'Preview',
       'Source image', 'Last update', 'Times', 'First date - Beginning',
       'First date - End', 'Last date - Beginning', 'Last date - End',
       'Detailed times', 'Accessibility code', 'Accessibility', 'Place ID',
       'Coordinates', 'Place name', 'Address', 'Arrondissement', 'INSEE code',
       'Postal code', 'City', 'Department', 'Region', 'Country', 'Place image',
       'Credits for the place image', 'Phone number', 'Place website',
       'Place links', 'Place tags', 'Place description', 'Access',
       'Physical or online event', 'Online access link', 'Status',
       'Minimum age', 'Maximum age', 'Source agenda (title)',
       'Source agenda (uid)', 'Contributor email', 'Contributor phone number',
       'Contributor name', 'Contributor function', 'Contributor organisation',
       'Category', 'Country name', 'Registration', 'Additionnal links'],
      dtype='object')

In [11]:
df = df.drop(columns=[
    'ID',
    'Slug',
    'Keywords', 
    'Credits for the image',
    'Source image',
    'Last update',
    'Detailed times',
    'Accessibility code',
    'Place ID',
    'Coordinates',
    'INSEE code',
    'Country',
    'Credits for the place image',
    'Place links', 
    'Place tags',
    'Place description',
    'Physical or online event',
    'Status',
    'Source agenda (uid)',
    'Contributor email', 
    'Contributor phone number',
    'Contributor name', 
    'Contributor function', 
    'Contributor organisation',
    'Category', 
    'Country name', 
    'Registration', 
    'Additionnal links'
    ])

In [12]:
df

,URL,Title,Description,Long description,Details,Image,Preview,Times,First date - Beginning,First date - End,...,Department,Region,Place image,Phone number,Place website,Access,Online access link,Minimum age,Maximum age,Source agenda (title)
5,https://openagenda.com/lete-culturel-2023-en-i...,Fanfare M'Brass - Fontenay-sous-Soleil,Été culturel 2023,<p>A l'occasion de <strong>Fontenay-sous-Solei...,NaN,https://cibul.s3.amazonaws.com/cdd462a7816a4e6...,https://cibul.s3.amazonaws.com/cdd462a7816a4e6...,"Samedi 8 juillet, 18h00",2023-07-08T18:00:00+02:00,2023-07-08T19:30:00+02:00,...,Val-de-Marne,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eté culturel 2023 : Île-de-France
9,https://openagenda.com/centre-tignous-dart-con...,BESTIOLES ÉLECTRONIQUES,Un projet de résidence de l’artiste Marylou - ...,<p>La résidence artistique de <strong>MARYLOU<...,Entrée libre - Ateliers sur inscription,https://cibul.s3.amazonaws.com/ef69bfc3e1a948e...,https://cibul.s3.amazonaws.com/ef69bfc3e1a948e...,10 février - 18 juin 2022,2022-02-10T19:00:00+01:00,2022-02-10T22:00:00+01:00,...,Seine-Saint-Denis,Île-de-France,https://cibul.s3.amazonaws.com/location1936457...,01 71 89 28 00,http://www.centretignousdartcontemporain.fr,Entrée libre,NaN,NaN,NaN,Centre Tignous d'Art Contemporain
11,https://openagenda.com/hormur-plateforme-deven...,"""Kafka Revisitée : Théâtre Intime à Romainvill...",Kafka réinventé à Romainville chez Big Box. La...,<p>Rejoignez-nous le 14 décembre à Romainville...,NaN,https://cdn.openagenda.com/main/e4f5dd77835c4d...,https://cdn.openagenda.com/main/e4f5dd77835c4d...,"Samedi 14 décembre 2024, 20h30",2024-12-14T20:30:00+01:00,2024-12-14T22:30:00+01:00,...,Seine-Saint-Denis,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hormur - Plateforme d'événements artistiques d...
21,https://openagenda.com/jnarchi-2024-ile-de-fra...,Femmes et architectes : elles font la ville (v...,Les métiers de la construction et les formatio...,<p>Les métiers de la construction et les forma...,NaN,https://cdn.openagenda.com/main/482b891c69924a...,https://cdn.openagenda.com/main/482b891c69924a...,"Dimanche 20 octobre 2024, 10h00",2024-10-20T10:00:00+02:00,2024-10-20T13:30:00+02:00,...,Seine-Saint-Denis,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Journées nationales de l’architecture 2024 : Î...
37,https://openagenda.com/jep-2024-ile-de-france/...,Visite libre de la chapelle orthodoxe Notre-Da...,La paroisse orthodoxe Notre-Dame-Joie-des-Affl...,<p>La paroisse orthodoxe Notre-Dame-Joie-des-A...,NaN,https://cdn.openagenda.com/main/4624d2618f714d...,https://cdn.openagenda.com/main/4624d2618f714d...,"Dimanche 22 septembre 2024, 14h00",2024-09-22T14:00:00+02:00,2024-09-22T16:30:00+02:00,...,Paris,Île-de-France,https://cdn.openagenda.com/main/location118188...,0698654849,https://ndjasg.fr/,NaN,NaN,NaN,NaN,Journées européennes du patrimoine 2024 : Île-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909865,https://openagenda.com/printemps-des-cimetiere...,"LE CIMETIÈRE DU NORD, DIT DE MONTMARTRE",Découvrez l'histoire et le patrimoine du site,<p>Proposée par la Ville de Paris. À l’occasio...,Entrée libre,https://cdn.openagenda.com/main/9f3056fa457048...,https://cdn.openagenda.com/main/9f3056fa457048...,"Dimanche 18 mai, 10h00",2025-05-18T10:00:00+02:00,2025-05-18T17:30:00+02:00,...,Paris,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025
909866,https://openagenda.com/printemps-des-cimetiere...,EN PARLER NE FAIT PAS MOURIR,Testez vos connaissances funéraires en défiant...,<p>Animation proposée par la Ville de Paris : ...,Entrée libre,https://cdn.openagenda.com/main/895b74d71d3346...,https://cdn.openagenda.com/main/895b74d71d3346...,"Dimanche 18 mai, 11h00",2025-05-18T11:00:00+02:00,2025-05-18T17:30:00+02:00,...,Val-de-Marne,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025
909867,https://openagenda.com/printemps-des-cimetiere...,BALADE CHANTÉE,A la découverte des auteurs inhumés au cimetiè...,<p>Avec l’association Le Petit Ney. Devant cha...,Entrée libre,https://cdn.openagenda.com/main/777de5fdb6ba48...,https://cdn.openagenda.com/main/777de5fdb6ba48...,"Dimanche 18 mai, 10h30, 15h00",2025-05-18T10:30:00+02:00,2025-05-18T12:30:00+02:00,...,Paris,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025
909885,https://openagenda.com/versailles-palais-des-c...,Jenifer - Jukebox Tour,Concert variété française,"<p>JUKE BOX TOUR Votre playlist, votre concert...",75 € Carré or / 69 € Cat 1 / 59 € Cat 2,https://cdn.openagenda.com/main/bd1c2a0b088248...,https://cdn.openagenda.com/main/bd1c2a0b088248...,"Samedi 6 décembre, 20h30",2025-12-06T20:30:00+01:00,2025-12-06T22:30:00+01:00,...,Yvelines,Île-de-France,NaN,NaN,NaN,NaN,NaN,9.0,99.0,Versailles Palais des Congrès
909889,https://openagenda.com/nuit-internationale-de-...,Nuit de la chauve-souris au Grand-Voyeux,A l’occasion de la Nuit Internationale de la c...,<p>Une présentation en début d’animation vous ...,"Sur inscription, gratuit",https://cdn.openagenda.com/main/45d39d235fe64c...,https://cdn.openagenda.com/main/45d39d235fe64c...,"Samedi 23 août, 20h00",2025-08-23T20:00:00+02:00,2025-08-23T23:00:00+02:00,...,Seine-et-Marne,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nuit Internationale de la Chauve-Souris

In [13]:
df["First date - Start - Date"] = pd.to_datetime(df["First date - Beginning"])
df

C:\Users\marie\AppData\Local\Temp\ipykernel_1792\990548965.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df["First date - Start - Date"] = pd.to_datetime(df["First date - Beginning"])

,URL,Title,Description,Long description,Details,Image,Preview,Times,First date - Beginning,First date - End,...,Region,Place image,Phone number,Place website,Access,Online access link,Minimum age,Maximum age,Source agenda (title),First date - Start - Date
5,https://openagenda.com/lete-culturel-2023-en-i...,Fanfare M'Brass - Fontenay-sous-Soleil,Été culturel 2023,<p>A l'occasion de <strong>Fontenay-sous-Solei...,NaN,https://cibul.s3.amazonaws.com/cdd462a7816a4e6...,https://cibul.s3.amazonaws.com/cdd462a7816a4e6...,"Samedi 8 juillet, 18h00",2023-07-08T18:00:00+02:00,2023-07-08T19:30:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eté culturel 2023 : Île-de-France,2023-07-08 18:00:00+02:00
9,https://openagenda.com/centre-tignous-dart-con...,BESTIOLES ÉLECTRONIQUES,Un projet de résidence de l’artiste Marylou - ...,<p>La résidence artistique de <strong>MARYLOU<...,Entrée libre - Ateliers sur inscription,https://cibul.s3.amazonaws.com/ef69bfc3e1a948e...,https://cibul.s3.amazonaws.com/ef69bfc3e1a948e...,10 février - 18 juin 2022,2022-02-10T19:00:00+01:00,2022-02-10T22:00:00+01:00,...,Île-de-France,https://cibul.s3.amazonaws.com/location1936457...,01 71 89 28 00,http://www.centretignousdartcontemporain.fr,Entrée libre,NaN,NaN,NaN,Centre Tignous d'Art Contemporain,2022-02-10 19:00:00+01:00
11,https://openagenda.com/hormur-plateforme-deven...,"""Kafka Revisitée : Théâtre Intime à Romainvill...",Kafka réinventé à Romainville chez Big Box. La...,<p>Rejoignez-nous le 14 décembre à Romainville...,NaN,https://cdn.openagenda.com/main/e4f5dd77835c4d...,https://cdn.openagenda.com/main/e4f5dd77835c4d...,"Samedi 14 décembre 2024, 20h30",2024-12-14T20:30:00+01:00,2024-12-14T22:30:00+01:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hormur - Plateforme d'événements artistiques d...,2024-12-14 20:30:00+01:00
21,https://openagenda.com/jnarchi-2024-ile-de-fra...,Femmes et architectes : elles font la ville (v...,Les métiers de la construction et les formatio...,<p>Les métiers de la construction et les forma...,NaN,https://cdn.openagenda.com/main/482b891c69924a...,https://cdn.openagenda.com/main/482b891c69924a...,"Dimanche 20 octobre 2024, 10h00",2024-10-20T10:00:00+02:00,2024-10-20T13:30:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Journées nationales de l’architecture 2024 : Î...,2024-10-20 10:00:00+02:00
37,https://openagenda.com/jep-2024-ile-de-france/...,Visite libre de la chapelle orthodoxe Notre-Da...,La paroisse orthodoxe Notre-Dame-Joie-des-Affl...,<p>La paroisse orthodoxe Notre-Dame-Joie-des-A...,NaN,https://cdn.openagenda.com/main/4624d2618f714d...,https://cdn.openagenda.com/main/4624d2618f714d...,"Dimanche 22 septembre 2024, 14h00",2024-09-22T14:00:00+02:00,2024-09-22T16:30:00+02:00,...,Île-de-France,https://cdn.openagenda.com/main/location118188...,0698654849,https://ndjasg.fr/,NaN,NaN,NaN,NaN,Journées européennes du patrimoine 2024 : Île-...,2024-09-22 14:00:00+02:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909865,https://openagenda.com/printemps-des-cimetiere...,"LE CIMETIÈRE DU NORD, DIT DE MONTMARTRE",Découvrez l'histoire et le patrimoine du site,<p>Proposée par la Ville de Paris. À l’occasio...,Entrée libre,https://cdn.openagenda.com/main/9f3056fa457048...,https://cdn.openagenda.com/main/9f3056fa457048...,"Dimanche 18 mai, 10h00",2025-05-18T10:00:00+02:00,2025-05-18T17:30:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025,2025-05-18 10:00:00+02:00
909866,https://openagenda.com/printemps-des-cimetiere...,EN PARLER NE FAIT PAS MOURIR,Testez vos connaissances funéraires en défiant...,<p>Animation proposée par la Ville de Paris : ...,Entrée libre,https://cdn.openagenda.com/main/895b74d71d3346...,https://cdn.openagenda.com/main/895b74d71d3346...,"Dimanche 18 mai, 11h00",2025-05-18T11:00:00+02:00,2025-05-18T17:30:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025,2025-05-18 11:00:00+02:00
909867,https://openagenda.com/printemps-des-cimetiere...,BALADE CHANTÉE,A la découverte des auteurs inhumés au cimetiè...,<p>Avec l’association Le Petit Ney. Devant cha...,Entrée libre,https://cdn.openagenda.com/main/777de5fdb6ba48...,https://cdn.openagenda.com/main/777de5fdb6ba48...,"Dimanche 18 mai, 10h30, 15h00",2025-05-18T10:30:00+02:00,2025-05-18T12:30:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Printemps des cimetières 2025,2025-05-18 10:30:00+02:00
909885,https://openagenda.com/versailles-palais-des-c...,Jenifer - Jukebox Tour,Concert variété française,"<p>JUKE BOX TOUR Votre playlist, votre concert...",75 € Carré or / 69 € Cat 1 / 59 € Cat 2,https://cdn.openagenda.com/main/bd1c2a0b088248...,https://cdn.openagenda.com/main/bd1c2a0b088248...,"Samedi 6 décembre, 20h30",2025-12-06T20:30:00+01:00,2025-12-06T22:30:00+01:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,9.0,99.0,Versailles Palais des Congrès,2025-12-06 20:30:00+01:00
909889,https://openagenda.com/nuit-internationale-de-...,Nuit de la chauve-souris au Grand-Voyeux,A l’occasion de la Nuit Internationale de la c...,<p>Une présentation en début d’animation vous ...,"Sur inscription, gratuit",https://cdn.openagenda.com/main/45d39d235fe64c...,https://cdn.openagenda.com/main/45d39d235fe64c...,"Samedi 23 août, 20h00",2025-08-23T20:00:00+02:00,2025-08-23T23:00:00+02:00,...,Île-de-France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nuit Internationale de la Chauve-Souris,2025-08-23 20:00:00+02:00

In [ ]:

https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/evenements-publics-openagenda/records?select=canonicalurl%20as%20URL%2C%20%20title_fr%20as%20Titre%2C%20%20description_fr%20as%20description%2C%20%20longdescription_fr%20as%20description_longue%20%2C%20image%20%2C%20thumbnail%20%2C%20daterange_fr%20as%20date%2C%20firstdate_end%20as%20premier_jour_debut%20%2C%20lastdate_begin%20as%20premier_jour_fin%20%2C%20lastdate_end%20as%20dernier_jour_debut%20%2C%20accessibility_label_fr%20as%20dernier_jour_fin%20%2C%20location_name%20as%20nom_localisation%20%2C%20location_address%20as%20adresse%20%2C%20location_postalcode%20as%20code_postale%20%2C%20location_city%20as%20ville%20%2C%20location_phone%20as%20telephone%20%2C%20location_website%20as%20site_web%20%2C%20location_description_fr%20as%20description_localisation%20%2C%20onlineaccesslink%20as%20lien_acces_en_ligne%20%2C%20age_min%20as%20age_minimum%20%2C%20age_max%20as%20age_maximum%20%2C%20originagenda_title%20as%20source&limit=20&refine=location_region%3A%22Martinique%22&refine=firstdate_begin%3A%222025%22

Index(['URL', 'Title', 'Description', 'Long description', 'Details', 'Image',
       'Preview', 'Times', 'First date - Beginning', 'First date - End',
       'Last date - Beginning', 'Last date - End', 'Accessibility',
       'Place name', 'Address', 'Arrondissement', 'Postal code', 'City',
       'Department', 'Region', 'Place image', 'Phone number', 'Place website',
       'Access', 'Online access link', 'Minimum age', 'Maximum age',
       'Source agenda (title)', 'First date - Start - Date'],
      dtype='object')

In [ ]:
import locale
from datetime import datetime

locale.setlocale(locale.LC_TIME, "fr_FR")

ModuleNotFoundError: No module named 'dateparser'

ModuleNotFoundError: No module named 'swagger'

In [17]:
df['date_test'] = df['Times'].apply(
    lambda x: datetime.strptime(x, "%A %d %B %Y, %Hh%M")
)
df['date_test'].dtype

ValueError: time data 'Samedi 8 juillet, 18h00' does not match format '%A %d %B %Y, %Hh%M'

In [ ]:
df["First date - Beginning"] = pd.to_datetime(
    df["First date - Beginning"], 
    format='ISO8601', 
    errors='coerce' 
)
df

C:\Users\marie\AppData\Local\Temp\ipykernel_27816\3066937276.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df["First date - Beginning"] = pd.to_datetime(

,ID,Slug,URL,Title,Description,Long description,Details,Keywords,Image,Credits for the image,...,Source agenda (uid),Contributor email,Contributor phone number,Contributor name,Contributor function,Contributor organisation,Category,Country name,Registration,Additionnal links
0,15268997,atelier-creation-dentreprise-3243132,https://openagenda.com/pole-emploi/events/atel...,Atelier Création d'Entreprise,Présentations des accompagnements mobilisables...,<p>Présentations des accompagnements mobilisab...,NaN,"Atelier,ReStart,Création d'entreprise,S'inform...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
1,50737223,la-classe-loeuvre--6944943,https://openagenda.com/ndm-2024-nouvelle-aquit...,"La classe, l'oeuvre !",Des élèves des lycées Jean Monnet (Blanquefort...,<p>Des élèves des lycées Jean Monnet (Blanquef...,Entrée libre,NaN,https://cibul.s3.amazonaws.com/72227a8a43014ed...,©Frédéric Deval,...,5795929.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),NaN,NaN
2,92831157,visite-atelier-adultesenfants,https://openagenda.com/ndm-2024-occitanie/even...,Visite-Atelier adultes/enfants,"Une visite de l'exposition ""Artistes et paysan...","<p>Une visite de l'exposition ""Artistes et pay...","Entrée libre, sur inscription pour 15 personnes",NaN,https://cibul.s3.amazonaws.com/064c6c38e4554e3...,"© les Abattoirs, Musée- Frac Occitanie Toulouse",...,5865786.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""reservation@lesab...",NaN
3,53456762,les-jeudis-de-linsertion-4071122,https://openagenda.com/francetravail/events/le...,Les jeudis de l'insertion,Les entreprises d'insertion viennent à votre r...,<p>Les entreprises d'insertion viennent à votr...,NaN,"Job dating,#TousMobilisés,Recrutement,S'inform...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
4,67676934,formation-cap-metiers-de-bouche-boucherboulang...,https://openagenda.com/francetravail/events/fo...,FORMATION CAP métiers de bouche (Boucher/Boula...,Vous souhaitez vous former et obtenir l'un des...,<p>Vous souhaitez vous former et obtenir l'un ...,NaN,"Réunion d'information,S'informer,Découverte fo...",NaN,NaN,...,38495884.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909885,77335011,jenifer-2381838,https://openagenda.com/versailles-palais-des-c...,Jenifer - Jukebox Tour,Concert variété française,"<p>JUKE BOX TOUR Votre playlist, votre concert...",75 € Carré or / 69 € Cat 1 / 59 € Cat 2,"Jukebox,Chanson Française,Jenifer",https://cdn.openagenda.com/main/bd1c2a0b088248...,NaN,...,27597051.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""billetterie@versa...",NaN
909886,33054961,rencontre-inter-degre-srav-usep-unss-4669373,https://openagenda.com/velodays/events/rencont...,Rencontre inter-degré SRAV USEP - UNSS,Itinéraire en trois étapes d'une délégation d'...,<p>De 9 h à 15 h 30 itinéraire de la délégatio...,NaN,Scolaire - Mobilité - Rencontre,https://cdn.openagenda.com/main/3de21e5f146943...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),NaN,NaN
909887,3102394,fete-du-velo-au-centre-juno-beach-1090822,https://openagenda.com/velodays/events/fete-du...,Vélodays : Fête du vélo au Centre Juno Beach,"Lors de cette journée, venez à la rencontre de...","<p>À l'occasion des Vélodays, le Centre Juno B...",NaN,Village - Vélo - Animations,https://cdn.openagenda.com/main/3b3e47586f214d...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""contact@coeurdena...",NaN
909888,76863502,mobilite-active-a-velobus-et-velocoque-esat-pa...,https://openagenda.com/velodays/events/mobilit...,Mobilité active à vélobus et vélocoque ESAT Pa...,Balade à vélo-bus et vélo-coque dans les parc...,<p>L'association V-LOW à Caen propose de prati...,NaN,Mobilité - Balade - Handicap,https://cdn.openagenda.com/main/dce1669b0fe342...,NaN,...,49236116.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""email"", ""value"": ""v-lowasso.caen@ou...",NaN
909889,14608802,nuit-de-la-chauve-souris-au-grand-voyeux-3859697,https://openagenda.com/nuit-internationale-de-...,Nuit de la chauve-souris au Grand-Voyeux,A l’occasion de la Nuit Internationale de la c...,<p>Une présentation en début d’animation vous ...,"Sur inscription, gratuit","chauve-souris,nuit,nocturne,balade",https://cdn.openagenda.com/main/45d39d235fe64c...,Théo Hurtrel,...,54441221.0,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://www.iledef...","[{""link"": ""https://www.iledefrance-nature.fr/s..."